version: '3.8'

services:
  collatz_api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    depends_on:
      - collatz_service

  collatz_service:
    build: .
    command: python collatz.py
    volumes:
      - .:/app
